<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <AssemblyName>blazor-test-app</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <IsTrimmable>false</IsTrimmable>
		<EnableTrimAnalyzer>false</EnableTrimAnalyzer>
		<PublishTrimmed>false</PublishTrimmed>
    </PropertyGroup>

</Project>